#!/usr/bin/env Rscript --vanilla

# Plot coverage matrix generated by e.g. 'mccortex31 links --covg-hist out.csv ...'
#
args <- commandArgs(trailingOnly=TRUE)
if(length(args) < 2 || length(args) > 3) {
  stop("Usage: Rscript --vanilla link-cov-heatmap.R <covg.csv> <out.pdf> [cutoff]\n")
}

cutoff=0
input_csv=args[1]
output_pdf=args[2]
if(length(args) > 2) { cutoff=args[3] }

library('ggplot2')
library('reshape')
library('scales')
library('plyr')

# d = matrix(1:9,nrow=3,ncol=3)
# d.m <- melt(d, varnames=c("dist","cov"))

# file='proj/k31/links/ben.se.thresh.csv'
r = read.table(input_csv,sep=',',head=T,row.names=1,comment.char='#')
d.m <- melt(as.matrix(r), varnames=c("dist","cov"))
d.m <- ddply(d.m, .(dist), transform, rescale = rescale(value))
xticks=seq(10,nrow(r),10)
if(nrow(r) < 10) { xticks=1:nrow(r); }
yticks=seq(0,ncol(r)-1,10) # y starts from zero, -1 on scale
p <- ggplot(d.m, aes(dist, cov)) +
     geom_tile(aes(fill = rescale), color = "white") +
     scale_fill_gradient(low = "white", high = "steelblue") +
     ggtitle("Link coverage") +
     scale_x_discrete(name="Distance (kmers)", breaks=rownames(r)[xticks], labels=xticks) +
     scale_y_discrete(name="Coverage", breaks=colnames(r)[yticks+1], labels=yticks)

if(cutoff > 0) {
  cutline <- data.frame(x=as.numeric(c(0,ncol(r))),y=as.numeric(c(cutoff,cutoff)))
  p <- p + geom_line(data=cutline, aes(x=x,y=y), color="black")
}

ggsave(p, file=output_pdf, width=6, height=6)
