#!/usr/bin/env Rscript --vanilla
## modified by: JFSanchezHerrero: https://github.com/JFsanchezherrero
## 28 March, 2019

# Plot coverage histograms generated by e.g. 'mccortex31 clean --length-before out.csv ...'
# input csv should have the columns: 'bp' and 'Count'
#
args <- commandArgs(trailingOnly=TRUE)
if(length(args) != 3) {
  stop("Usage: Rscript --vanilla plot-hist-hist.R <raw_lengths.csv> <clean_lengths.csv> <lengths.pdf>\n")
}

raw_input_csv = args[1]
clean_input_csv = args[2]
output_pdf = args[3]

library('ggplot2')
library('gridExtra')

plot_length <- function(fileGiven, colourGiven, titleGiven) {

  d=read.csv(file=fileGiven, sep=',',as.is=T)
  
  p <- ggplot(data=d, aes(bp, Count)) +
    geom_bar(stat="identity", color=colourGiven, fill=colourGiven) +
    scale_y_log10() +
    xlab("Untig length (bases)") +
    ylab("Number of unitigs") +
    ggtitle(titleGiven)
  
  return(list("plot" = p))

}

raw <- plot_length(fileGiven = raw_input_csv, colourGiven = "seagreen", titleGiven = "Raw Unitig Length")
clean <- plot_length(fileGiven = clean_input_csv , colourGiven = "red", titleGiven = "Clean Unitig Length")

pdf(output_pdf,width=12,height=6)
grid.arrange(raw$plot, clean$plot, ncol=2)
dev.off()