#!/usr/bin/env Rscript --vanilla

# Plot coverage histograms generated by e.g. 'mccortex31 clean --covg-before out.csv ...'
# input csv should have the columns: 'Covg' and 'NumUnitigs'
#
args <- commandArgs(trailingOnly=TRUE)
if(length(args) != 2) {
  stop("Usage: Rscript --vanilla plot-covg-hist.R <covg.csv> <out.pdf>\n")
}

input_csv=args[1]
output_pdf=args[2]

library('ggplot2')
library('gridExtra')

d=read.csv(file=input_csv,sep=',',as.is=T)

p <- ggplot(data=d, aes(x=Covg, y=NumKmers)) +
       geom_bar(stat="identity") +
       xlab("Coverage (X)") +
       ylab("Number of kmers") +
       ggtitle("Kmer Coverage") +
       xlim(0,150)

q <- ggplot(data=d, aes(x=Covg, y=NumUnitigs)) +
       geom_bar(stat="identity") +
       xlab("Coverage (X)") +
       ylab("Number of unitigs") +
       ggtitle("Unitig Median Coverage") +
       xlim(0,150)

pdf(output_pdf,width=12,height=6)
grid.arrange(p, q, ncol=2)
dev.off()
