# Plot coverage histograms generated by e.g. 'ctx31 clean --covgs out.csv ...'
# input csv should have the columns: 'Covg' and 'Supernodes'
#
args <- commandArgs(trailingOnly=TRUE)
if(length(args) != 2) {
  stop("Usage: R --vanilla --file=plot-covg-hist.R --args <covg.csv> <out.pdf>\n")
}

input_csv=args[1]
output_pdf=args[2]

library(ggplot2)

d=read.csv(file=input_csv,sep=',',as.is=T)

p <- ggplot(data=d, aes(x=Covg, y=Supernodes)) +
       geom_bar(stat="identity") +
       xlab("Supernode Coverage (X)") +
       ylab("Number of Supernodes") +
       ggtitle("Supernode Coverage Distribution")

ggsave(filename=output_pdf, plot=p, width=max(6,max(d[,'Covg'])/50), height=6)
