# Plot coverage histograms generated by e.g. 'ctx31 clean --covgs out.csv ...'
# input csv should have the columns: 'Covg' and 'Supernodes'
#
args <- commandArgs(trailingOnly=TRUE)
if(length(args) != 2) {
  stop("Usage: R --vanilla --file=plot-covg-hist.R --args <covg.csv> <out.pdf>\n")
}

input_csv=args[1]
output_pdf=args[2]

require(ggplot2)
require(gridExtra)

d=read.csv(file=input_csv,sep=',',as.is=T)

p <- ggplot(data=d, aes(x=Covg, y=NumSupernodes)) +
       geom_bar(stat="identity") +
       xlab("Coverage (X)") +
       ylab("Number of Supernodes") +
       ggtitle("Supernode Coverage Distribution") +
       xlim(0,150)

q <- ggplot(data=d, aes(x=Covg, y=NumKmers)) +
       geom_bar(stat="identity") +
       xlab("Coverage (X)") +
       ylab("Number of kmers in supernodes") +
       ggtitle("Supernode Length-Coverage Distribution") +
       xlim(0,150)

pdf(output_pdf,width=12,height=6)
grid.arrange(p, q, ncol=2)
dev.off()
